"""
Automated Supabase Migration Script

This script will automatically update all your configuration files
with new Supabase credentials after you create the project.

Usage:
1. Create new Supabase project at https://supabase.com/dashboard
2. Copy your credentials
3. Run this script and paste when prompted
4. Script updates all files automatically
"""

import os
from pathlib import Path
import re

def get_credentials():
    """Prompt user for new Supabase credentials."""
    print("=" * 60)
    print("SUPABASE MIGRATION - CREDENTIAL INPUT")
    print("=" * 60)
    print()
    print("Please provide your new Supabase project credentials:")
    print("(You can find these in Supabase Dashboard → Settings → API)")
    print()
    
    credentials = {}
    
    # Project URL
    print("1. Project URL")
    print("   Example: https://abcdefghijk.supabase.co")
    credentials['url'] = input("   Enter: ").strip()
    print()
    
    # Anon Key
    print("2. Anon/Public Key (starts with 'eyJ...')")
    credentials['anon_key'] = input("   Enter: ").strip()
    print()
    
    # JWT Secret
    print("3. JWT Secret (from Settings → API)")
    credentials['jwt_secret'] = input("   Enter: ").strip()
    print()
    
    # Database Password
    print("4. Database Password (you set this when creating project)")
    credentials['db_password'] = input("   Enter: ").strip()
    print()
    
    # Extract project ref from URL
    match = re.search(r'https://([^.]+)\.supabase\.co', credentials['url'])
    if match:
        credentials['project_ref'] = match.group(1)
    else:
        print("⚠️  Could not extract project ref from URL")
        credentials['project_ref'] = input("   Enter project ref manually: ").strip()
    
    return credentials

def update_frontend_env_local(creds):
    """Update frontend/.env.local"""
    path = Path("../frontend/.env.local")
    
    if not path.exists():
        print(f"⚠️  {path} not found, skipping")
        return
    
    with open(path, 'r') as f:
        content = f.read()
    
    # Update Supabase URL
    content = re.sub(
        r'VITE_SUPABASE_URL=.*',
        f'VITE_SUPABASE_URL={creds["url"]}',
        content
    )
    
    # Update Anon Key
    content = re.sub(
        r'VITE_SUPABASE_ANON_KEY=.*',
        f'VITE_SUPABASE_ANON_KEY={creds["anon_key"]}',
        content
    )
    
    with open(path, 'w') as f:
        f.write(content)
    
    print(f"✓ Updated {path}")

def update_frontend_env_production(creds):
    """Update frontend/.env.production"""
    path = Path("../frontend/.env.production")
    
    if not path.exists():
        print(f"⚠️  {path} not found, skipping")
        return
    
    with open(path, 'r') as f:
        content = f.read()
    
    # Update Supabase URL
    content = re.sub(
        r'VITE_SUPABASE_URL=.*',
        f'VITE_SUPABASE_URL={creds["url"]}',
        content
    )
    
    # Update Anon Key
    content = re.sub(
        r'VITE_SUPABASE_ANON_KEY=.*',
        f'VITE_SUPABASE_ANON_KEY={creds["anon_key"]}',
        content
    )
    
    with open(path, 'w') as f:
        f.write(content)
    
    print(f"✓ Updated {path}")

def update_backend_env(creds):
    """Update backend/.env"""
    path = Path(".env")
    
    if not path.exists():
        print(f"⚠️  {path} not found, skipping")
        return
    
    with open(path, 'r') as f:
        content = f.read()
    
    # Update JWT Secret
    content = re.sub(
        r'SUPABASE_JWT_SECRET=.*',
        f'SUPABASE_JWT_SECRET={creds["jwt_secret"]}',
        content
    )
    
    with open(path, 'w') as f:
        f.write(content)
    
    print(f"✓ Updated {path}")

def create_production_env(creds):
    """Create backend/.env.production for Railway"""
    path = Path(".env.production")
    
    # Build DATABASE_URL
    db_url = f"postgresql://postgres.{creds['project_ref']}:{creds['db_password']}@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres"
    
    content = f"""# Production Environment Variables for Railway
# Auto-generated by migrate_supabase.py

DATABASE_URL={db_url}
SUPABASE_JWT_SECRET={creds['jwt_secret']}
OPENROUTER_API_KEY=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
ALLOWED_ORIGINS=https://zunofrontendf.vercel.app,http://localhost:5173
"""
    
    with open(path, 'w') as f:
        f.write(content)
    
    print(f"✓ Created {path}")

def print_next_steps(creds):
    """Print next steps for user."""
    print()
    print("=" * 60)
    print("NEXT STEPS")
    print("=" * 60)
    print()
    
    print("1. UPDATE VERCEL ENVIRONMENT VARIABLES")
    print("   Go to: https://vercel.com/dashboard")
    print("   → Select 'zunofrontendf' project")
    print("   → Settings → Environment Variables")
    print()
    print("   Update these:")
    print(f"   VITE_SUPABASE_URL={creds['url']}")
    print(f"   VITE_SUPABASE_ANON_KEY={creds['anon_key']}")
    print()
    print("   Then: Deployments → Redeploy")
    print()
    
    print("2. UPDATE RAILWAY ENVIRONMENT VARIABLES")
    print("   Go to: https://railway.com/dashboard")
    print("   → Select 'zuno-production' project")
    print("   → Variables tab")
    print()
    print("   Update these:")
    db_url = f"postgresql://postgres.{creds['project_ref']}:{creds['db_password']}@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres"
    print(f"   DATABASE_URL={db_url}")
    print(f"   SUPABASE_JWT_SECRET={creds['jwt_secret']}")
    print()
    print("   Railway will auto-redeploy")
    print()
    
    print("3. INITIALIZE DATABASE")
    print("   Run: python init_supabase_db.py")
    print()
    
    print("4. CONFIGURE SUPABASE AUTH")
    print("   Go to: Supabase Dashboard → Authentication → URL Configuration")
    print("   Site URL: https://zunofrontendf.vercel.app")
    print("   Redirect URLs:")
    print("     - https://zunofrontendf.vercel.app/**")
    print("     - http://localhost:5173/**")
    print()
    
    print("5. RESTART LOCAL SERVERS")
    print("   Backend: docker-compose down && docker-compose up")
    print("   Frontend: npm run dev (restart)")
    print()
    
    print("6. TEST")
    print("   Local: http://localhost:5173")
    print("   Production: https://zunofrontendf.vercel.app")
    print()

def main():
    print()
    print("🚀 SUPABASE MIGRATION AUTOMATION")
    print()
    print("This script will automatically update all configuration files")
    print("with your new Supabase project credentials.")
    print()
    
    # Get credentials
    creds = get_credentials()
    
    # Confirm
    print()
    print("=" * 60)
    print("CONFIRMATION")
    print("=" * 60)
    print()
    print(f"Project URL: {creds['url']}")
    print(f"Project Ref: {creds['project_ref']}")
    print(f"Anon Key: {creds['anon_key'][:20]}...")
    print(f"JWT Secret: {creds['jwt_secret'][:20]}...")
    print()
    
    response = input("Update all files with these credentials? (yes/no): ")
    if response.lower() not in ['yes', 'y']:
        print("Cancelled.")
        return
    
    print()
    print("=" * 60)
    print("UPDATING FILES")
    print("=" * 60)
    print()
    
    # Update files
    update_frontend_env_local(creds)
    update_frontend_env_production(creds)
    update_backend_env(creds)
    create_production_env(creds)
    
    print()
    print("✅ All local files updated!")
    print()
    
    # Print next steps
    print_next_steps(creds)
    
    print("=" * 60)
    print("MIGRATION SCRIPT COMPLETE")
    print("=" * 60)
    print()
    print("Follow the next steps above to complete the migration.")
    print()

if __name__ == "__main__":
    main()
